services:
  - type: web
    name: orbital-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: uvicorn myproject.asgi:application --host 0.0.0.0 --port 8000
    envVars:
      - key: postgresql://orbitaldb_user:TYD5T5db2HmsEUtEKz3zY2cn8yiG3rQj@dpg-d225mbe3jp1c738hb8l0-a/orbitaldb
        fromDatabase:
          name: orbitaldb
          property: connectionString

  - type: web
    name: orbital-frontend
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    buildCommand: ""
    startCommand: ""