# Generated by Django 5.2 on 2026-06-28 14:33

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', validators=[accounts.models.filesize_valid])),
                ('remarks', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('payment', models.CharField(choices=[('PayLah', 'PayLah'), ('PayNow', 'PayNow'), ('Cash', 'Cash'), ('NETS', 'NETS'), ('Card', 'Card'), ('Others', 'Others')], max_length=20)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('fundraiser_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='yet to start', max_length=20)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundraiser', to='listings.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundraisers.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fundraisers.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='VendorFundraiser',
            fields=[
                ('fundraiser_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_fundraiser', to='offers.joboffer')),
                ('org_fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='fundraisers.fundraiser')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fundraisers.vendorfundraiser'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('vendor_fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='fundraisers.vendorfundraiser')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='fundraisers.vendorfundraiser'),
        ),
    ]
