# Generated by Django 5.2 on 2025-07-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message'),
        ('core', '0002_profile'),
    ]

    operations = [
    ]
