# Generated by Django 5.2 on 2025-06-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_jobpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "value",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="id",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="post_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="keywords",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="keywords",
            field=models.ManyToManyField(blank=True, to="core.keyword"),
        ),
    ]
