# Generated by Django 5.2 on 2025-06-21 08:46

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_keyword_remove_jobpost_id_jobpost_post_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='commission',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 6, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='end_time',
            field=models.TimeField(default='17:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='National University of Singapore', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 6, 3)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='start_time',
            field=models.TimeField(default='08:00:00'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='core.organization'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
