# Generated by Django 5.2 on 2025-06-14 14:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_keyword_remove_jobpost_id_jobpost_post_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "quantity",
                    models.IntegerField(
                        verbose_name=django.core.validators.MinValueValidator(0)
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        verbose_name=django.core.validators.MinValueValidator(0)
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
    ]
