# Generated by Django 5.2 on 2025-07-24 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_profile_name_profile_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="rating_count",
        ),
        migrations.RemoveField(
            model_name="vendorfundraiser",
            name="revenue",
        ),
    ]
