# Generated by Django 5.2 on 2025-06-14 14:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="post_id",
            new_name="product_id",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="core.vendor",
            ),
        ),
    ]
