# Generated by Django 5.2 on 2025-06-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobpost_commission_jobpost_end_date_jobpost_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='content',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='remarks',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
