# Generated by Django 5.2 on 2025-07-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
