# Generated by Django 5.2 on 2025-06-23 02:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_jobpost_content_jobpost_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="post_attachments/",
                validators=[core.models.filesize_valid],
            ),
        ),
    ]
