# Generated by Django 5.2 on 2025-06-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_jobpost_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("value", models.CharField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="keywords",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="categories",
            field=models.ManyToManyField(blank=True, to="core.category"),
        ),
        migrations.DeleteModel(
            name="Keyword",
        ),
    ]
