# Generated by Django 5.2 on 2025-06-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_category_remove_jobpost_keywords_jobpost_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="value",
            field=models.CharField(
                choices=[
                    ("Food & Beverages", "Food & Beverages"),
                    ("Accessories", "Accessories"),
                    ("Stationery", "Stationery"),
                    ("Clothing", "Clothing"),
                    ("Toys", "Toys"),
                    ("Books", "Books"),
                    ("Home Decor", "Home Decor"),
                    ("Art & Crafts", "Art & Crafts"),
                    ("Tech Gadgets", "Tech Gadgets"),
                    ("Skincare & Beauty", "Skincare & Beauty"),
                    ("Plants", "Plants"),
                    ("Pet Supplies", "Pet Supplies"),
                ],
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
