# Generated by Django 5.2 on 2025-06-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_category_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="value",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
