# Generated by Django 5.2 on 2025-06-26 03:46

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_category_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                ("offer_id", models.AutoField(primary_key=True, serialize=False)),
                ("allDays", models.BooleanField()),
                (
                    "selectedDays",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("otherCategories", models.CharField(max_length=500)),
                (
                    "commission",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("remarks", models.TextField(blank=True, max_length=2000)),
                ("status", models.CharField()),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_offers",
                        to="core.jobpost",
                    ),
                ),
                (
                    "selectedCategories",
                    models.ManyToManyField(blank=True, to="core.category"),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_offers",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
    ]
