# Generated by Django 5.2 on 2025-06-26 03:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_joboffer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joboffer",
            old_name="post",
            new_name="listing",
        ),
    ]
