# Generated by Django 5.2 on 2025-06-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_rename_post_joboffer_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="otherCategories",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
