# Generated by Django 5.2 on 2025-06-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_joboffer_othercategories"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="inventory_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
