# Generated by Django 5.2 on 2025-06-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_joboffer_inventory_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='otherCategories',
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='inventory_file',
            field=models.FileField(blank=True, null=True, upload_to='inventory_file/'),
        ),
    ]
