# Generated by Django 5.2 on 2025-06-29 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_joboffer_inventory_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="inventory_file",
            field=models.FileField(blank=True, null=True, upload_to="inventory_file/"),
        ),
        migrations.CreateModel(
            name="Fundraiser",
            fields=[
                ("fundraiser_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_listings",
                        to="core.jobpost",
                    ),
                ),
                (
                    "vendors",
                    models.ManyToManyField(related_name="vendors", to="core.joboffer"),
                ),
            ],
        ),
    ]
