# Generated by Django 5.2 on 2025-06-29 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_joboffer_inventory_file_fundraiser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joboffer",
            name="otherCategories",
        ),
    ]
