# Generated by Django 5.2 on 2025-06-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_joboffer_inventory_file_fundraiser'),
        ('core', '0015_remove_joboffer_othercategories_and_more'),
    ]

    operations = [
    ]
