# Generated by Django 5.2 on 2025-06-29 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_merge_20250629_1536'),  
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraiser",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fundraisers",
                to="core.jobpost",
            ),
        ),
        migrations.AlterField(
            model_name="fundraiser",
            name="vendors",
            field=models.ManyToManyField(
                related_name="fundraisers", to="core.joboffer"
            ),
        ),
    ]
